version: "2"

services:
  app:
    build: .
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    links:
      - db
      - phpmyadmin

  db:
    image: mysql:5.7.30
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret

  phpmyadmin:
    image: phpmyadmin:5.0-apache
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=db